// GENERATED from assets/app.js — do not hand-edit.
//
// The website's own translation table, copied across so the app says the
// same words the site does. Content Khalid edits in the control panel is NOT
// here — that arrives from api.php?do=config and always wins over these.
// Regenerate with: dart run tool/sync_strings.dart
library;

const Map<String, Map<String, String>> uiStrings = {
  'ar': {
    'appName': 'ثـمـــن مــوتــرك',
    'tagline': 'أول خدمة تقييم مجانية في قطر',
    'freeBadge': 'مجاناً 100%',
    'heroTitle': 'كم تساوي مــوتــرك؟',
    'heroSub': 'صوّر مــوتــرك، أرسل الصور، واحصل على السعر التقديري. بدون رسوم.',
    's1Title': 'بيانات السيارة',
    's1Sub': 'الخطوة 1 من 4',
    'fMake': 'الشركة المصنعة',
    'fClass': 'الفئة',
    'fModel': 'الموديل / الفئة الفرعية',
    'fYear': 'سنة الصنع',
    'fKm': 'الممشى',
    'fReg': 'رقم الاستمارة (اختياري)',
    'fVin': 'رقم الشاصي / الهيكل (اختياري)',
    'fNotes': 'ملاحظات (اختياري)',
    'phNotes': 'حوادث، صبغ، إضافات...',
    'phMakeOther': 'اكتب اسم الشركة',
    'phClassOther': 'اكتب اسم الفئة',
    'selMake': '— اختر الشركة —',
    'selClass': '— اختر الفئة —',
    'selYear': '— اختر السنة —',
    'other': 'أخرى…',
    'otherYears': 'سنوات أخرى',
    's2Title': 'حالة السيارة',
    's2Sub': 'الخطوة 2 من 4',
    'cmTitle': 'حدّد الأجزاء المصبوغة أو المتضررة',
    'cmHint': 'اضغط على أي جزء مرة = صبغ، مرتين = حادث أو إصلاح، ثلاث مرات = إلغاء.',
    'cmClear': 'مسح التحديد',
    'cmLocked': 'اخترت «أصلي بالكامل» — لا يمكن تحديد أي جزء.',
    'cpTitle': 'حالة الصبغ',
    'ceTitle': 'هل الصبغ جزئي أم كامل؟',
    'errPaint': 'اختر حالة الصبغ أولاً.',
    'errExtent': 'اختر إن كان الصبغ جزئياً أم كاملاً.',
    'cpLockRepaint': 'حدّدت جزءاً كـ«حادث / إصلاح» على الرسم، لذلك لا يمكن اختيار «صبغ فقط».',
    'cpMoved': 'نقلنا اختيارك إلى «صبغ بعد حادث أو إصلاح».',
    'sendingTitle': 'جارٍ رفع الصور…',
    'sendingWarn': 'لا تغلق هذه الصفحة حتى ينتهي الرفع.',
    'sendingWork': 'جارٍ المعالجة…',
    'sendingWorkSub': 'لحظات ونعطيك رقم الطلب.',
    's3Title': 'صور السيارة',
    's3Sub': 'الخطوة 3 من 4',
    'slotHint': 'كل صندوق يوضّح الزاوية المطلوبة. اضغط «كاميرا» للتصوير مباشرة أو «من الجهاز» لاختيار صورة محفوظة.',
    'camera': 'كاميرا',
    'device': 'الجهاز',
    'retake': 'تغيير الصورة',
    'reqTag': 'مطلوب',
    'optTag': 'اختياري',
    'addVideos': 'أضف فيديو (اختياري)',
    'videoRule': 'حتى مقطعين — دوران حول السيارة وصوت المحرك',
    'addReport': 'أضف تقرير فحص (اختياري)',
    'reportRule': 'فحص فني (فحص) أو أي تقرير من جهة أخرى — PDF أو صورة',
    'reportFile': 'ملف',
    'reportCamera': 'كاميرا',
    's4Title': 'بياناتك',
    's4Sub': 'الخطوة 4 من 4 — سنرسل رقم طلبك والنتيجة على بريدك',
    'fName': 'الاسم',
    'fPhone': 'رقم الجوال',
    'fEmail': 'البريد الإلكتروني',
    'fKeep': 'كم يوماً نحتفظ بصورك؟',
    'd3': '3 أيام',
    'd7': '7 أيام',
    'keepNote': 'تُحذف الصور والفيديو تلقائياً بعد هذه المدة.',
    'next': 'التالي',
    'back': 'رجوع',
    'send': 'إرسال الطلب',
    'sending': 'جارٍ الإرسال…',
    'sentTitle': 'تم استلام طلبك',
    'sentSub': 'احتفظ برقم الطلب — تدخل به بدون كلمة مرور.',
    'yourId': 'رقم طلبك',
    'sentMail': 'أرسلنا الرقم أيضاً إلى بريدك الإلكتروني.',
    'junkT': 'لم يصلك البريد؟',
    'junkB': 'تحقق من مجلد «الرسائل غير المرغوب فيها» (Junk / Spam). إن وجدته هناك، اضغط «ليس بريداً مزعجاً» حتى تصلك رسائلنا القادمة في البريد الوارد.',
    'junkS': 'ما زلت لا تجده؟ راسلنا من صفحة الدعم ←',
    'checkNow': 'تابع حالة الطلب',
    'another': 'تقييم سيارة أخرى',
    'stTitle': 'حالة طلبك',
    'stSub': 'أدخل رقم الطلب فقط — لا حاجة لكلمة مرور.',
    'fId': 'رقم الطلب',
    'check': 'استعلام',
    'checking': 'جارٍ الاستعلام…',
    'guideTitle': 'كيف تعمل الخدمة؟',
    'guideSub': 'دليل مختصر — الخطوات الخمس، وماذا تحصل عليه، والتطبيقات القادمة.',
    'overviewTitle': 'نبذة عنا',
    'overviewBody': '',
    'infoTitle': 'كيف تعمل الخدمة؟',
    'step1k': '1',
    'step1v': 'اختر بيانات موترك من القوائم.',
    'step2k': '2',
    'step2v': 'صوّر السيارة حسب الصناديق الثمانية.',
    'step3k': '3',
    'step3v': 'تستلم رقم طلب على الشاشة وعلى بريدك.',
    'step4k': '4',
    'step4v': 'ضوء أحمر = تحت المراجعة. ضوء أخضر = السعر جاهز.',
    'privTitle': 'الخصوصية',
    'privBody': 'صورك وفيديوهاتك تُحذف تلقائياً من الخادم بعد 3 أو 7 أيام حسب اختيارك. لا نشاركها مع أي جهة أخرى.',
    'cTitle': 'تواصل معنا',
    'cEmail': 'البريد',
    'cWeb': 'الموقع',
    'devCredit': 'تطوير: فاروق',
    'termsTitle': 'الشروط والأحكام',
    'privacyTitle': 'سياسة الخصوصية',
    'extraLink1Label': '',
    'extraLink2Label': '',
    'navEval': 'تقييم',
    'navStatus': 'حالة الطلب',
    'navInfo': 'معلومات',
    'navSupport': 'الدعم',
    'supportTitle': 'الدعم والاقتراحات',
    'supportIntro': 'واجهت مشكلة في الموقع؟ عندك اقتراح أو سؤال؟ اكتب لنا مباشرة من هنا وسنرد عليك.',
    'supKind': 'نوع الرسالة',
    'supMsg': 'رسالتك',
    'supMsgPh': 'اكتب المشكلة بالتفصيل — مثلاً: لم أجد شركة سيارتي في القائمة.',
    'supReach': 'اترك بريدك أو رقم جوالك حتى نتمكن من الرد عليك — واحد منهما يكفي.',
    'supRef': 'رقم الطلب (إن وجد)',
    'supSend': 'إرسال الرسالة',
    'supSending': 'جارٍ الإرسال…',
    'supThanksT': 'تم إرسال رسالتك',
    'supportThanks': 'وصلتنا رسالتك، شكراً لك. سنتواصل معك على البريد أو الجوال الذي كتبته.',
    'supRefNo': 'رقم المتابعة',
    'supAnother': 'إرسال رسالة أخرى',
    'errSupMsg': 'اكتب رسالتك أولاً (١٠ أحرف على الأقل).',
    'errSupContact': 'اترك بريداً إلكترونياً صحيحاً أو رقم جوال حتى نرد عليك.',
    'errSupMany': 'أرسلت رسائل كثيرة خلال وقت قصير. حاول بعد قليل.',
    'supFollowT': 'تابع رسالة سابقة',
    'supFollowS': 'عندك رقم متابعة؟ أدخله لترى إن كنا قرأنا رسالتك وردّينا عليها.',
    'supKeep': 'احتفظ بهذا الرقم — تتابع به رسالتك في أي وقت، وأرسلناه أيضاً إلى بريدك.',
    'errSupId': 'أدخل رقم المتابعة كاملاً.',
    'errSupNotFound': 'لم نجد هذا الرقم. تأكد منه وحاول مرة أخرى.',
    'supStNew': 'وصلت — بانتظار القراءة',
    'supStSeen': 'تمت القراءة',
    'supStReplied': 'تم الرد',
    'supYourMsg': 'رسالتك',
    'supOurReply': 'ردنا',
    'supSentOn': 'تاريخ الإرسال',
    'pdfDownload': 'تنزيل تقرير التقييم (PDF)',
    'footer': 'ثـمـــن مــوتــرك',
    'errFields': 'يرجى تعبئة الشركة والفئة والموديل وسنة الصنع والممشى.',
    'errModel': 'يرجى كتابة الموديل / الفئة الفرعية.',
    'errKm': 'يرجى كتابة الممشى بالأرقام (كم).',
    'errMissing': 'ناقص: {list}',
    'errVideoMax': 'الحد الأقصى {n} مقطع فيديو.',
    'errReportMax': 'الحد الأقصى {n} ملف للتقرير.',
    'errReportType': 'التقرير يجب أن يكون PDF أو صورة.',
    'errBig': 'الملف "{f}" كبير جداً (الحد {n} ميجابايت).',
    'errName': 'أدخل اسمك.',
    'errPhone': 'أدخل رقم جوال صحيح.',
    'errEmail': 'أدخل بريداً إلكترونياً صحيحاً.',
    'errNet': 'تعذّر الإرسال. تحقق من الاتصال وحاول مرة أخرى.',
    'errId': 'أدخل رقم الطلب المكوّن من 6 خانات.',
    'errNotFound': 'لم نجد هذا الرقم. تأكد منه وحاول مرة أخرى.',
    'counterOk': '{a} صور — كل الصور المطلوبة مكتملة ✔',
    'counterBad': '{a} من {b} صور مطلوبة',
    'underReview': 'تحت المراجعة',
    'underReviewSub': 'طلبك وصل. سنرسل السعر على بريدك فور جاهزيته.',
    'ready': 'التقييم جاهز',
    'readySub': 'هذا هو السعر التقديري لسيارتك.',
    'priceLabel': 'السعر التقديري',
    'priceRange': 'النطاق السعري التقديري',
    'carLabel': 'السيارة',
    'idLabel': 'رقم الطلب',
    'sentAt': 'تاريخ الإرسال',
    'filesUntil': 'تُحذف الملفات في',
    'filesCount': 'الملفات',
    'photosW': 'صور',
    'videosW': 'فيديو',
    'removed': 'تم الحذف',
    'noteLabel': 'ملاحظة من الفريق',
  },
  'en': {
    'appName': 'Evaluate Your Car',
    'tagline': 'First free valuation service in Qatar',
    'freeBadge': '100% FREE',
    'heroTitle': 'What is your car worth?',
    'heroSub': 'Photograph your car, send the pictures, get an estimated price. No fee.',
    's1Title': 'Car details',
    's1Sub': 'Step 1 of 4',
    'fMake': 'Make',
    'fClass': 'Class',
    'fModel': 'Model / trim',
    'fYear': 'Year',
    'fKm': 'Mileage',
    'fReg': 'Registration number (optional)',
    'fVin': 'Chassis / VIN (optional)',
    'fNotes': 'Notes (optional)',
    'phNotes': 'Accidents, repaint, extras…',
    'phMakeOther': 'Type the make',
    'phClassOther': 'Type the class',
    'selMake': '— Select make —',
    'selClass': '— Select class —',
    'selYear': '— Select year —',
    'other': 'Other…',
    'otherYears': 'Other years',
    's2Title': 'Car condition',
    's2Sub': 'Step 2 of 4',
    'cmTitle': 'Mark the repainted or damaged panels',
    'cmHint': 'Tap a panel once = repainted, twice = accident or repair, three times = clear.',
    'cmClear': 'Clear all',
    'cmLocked': 'You chose “fully original” — no panel can be marked.',
    'cpTitle': 'Paint status',
    'ceTitle': 'Partial or full respray?',
    'errPaint': 'Please choose the paint status first.',
    'errExtent': 'Please choose whether the respray was partial or full.',
    'cpLockRepaint': 'You marked a panel as “accident / repair” on the diagram, so “repainted only” cannot apply.',
    'cpMoved': 'We moved your answer to “Repainted after an accident / repair”.',
    'sendingTitle': 'Uploading your photos…',
    'sendingWarn': 'Please keep this page open until it finishes.',
    'sendingWork': 'Processing…',
    'sendingWorkSub': 'A moment — your request number is on its way.',
    's3Title': 'Car photos',
    's3Sub': 'Step 3 of 4',
    'slotHint': 'Each box shows the angle we need. Tap “Camera” to shoot it now, or “Gallery” to pick a saved photo.',
    'camera': 'Camera',
    'device': 'Gallery',
    'retake': 'Replace photo',
    'reqTag': 'required',
    'optTag': 'optional',
    'addVideos': 'Add video (optional)',
    'videoRule': 'Up to 2 clips — a walk-around and the engine sound',
    'addReport': 'Add an inspection report (optional)',
    'reportRule': 'FAHES or any third-party report — PDF or photo',
    'reportFile': 'File',
    'reportCamera': 'Camera',
    's4Title': 'Your details',
    's4Sub': 'Step 4 of 4 — we email you the request ID and the result',
    'fName': 'Full name',
    'fPhone': 'Mobile number',
    'fEmail': 'Email address',
    'fKeep': 'How long should we keep your files?',
    'd3': '3 days',
    'd7': '7 days',
    'keepNote': 'Photos and videos are deleted automatically after this period.',
    'next': 'Next',
    'back': 'Back',
    'send': 'Send request',
    'sending': 'Sending…',
    'sentTitle': 'Request received',
    'sentSub': 'Keep this ID — you log in with it, no password.',
    'yourId': 'Your request ID',
    'sentMail': 'We have also emailed the ID to you.',
    'junkT': 'Email not arrived?',
    'junkB': 'Check your Junk or Spam folder. If it is there, press “Not spam” — that way our next messages reach your inbox.',
    'junkS': 'Still cannot find it? Write to us on the Support page →',
    'checkNow': 'Check status',
    'another': 'Evaluate another car',
    'stTitle': 'Your request status',
    'stSub': 'Enter the request ID only — no password needed.',
    'fId': 'Request ID',
    'check': 'Check',
    'checking': 'Checking…',
    'guideTitle': 'How the service works',
    'guideSub': 'A short guide — the five steps, what you get, and the apps that are coming.',
    'overviewTitle': 'Overview',
    'overviewBody': '',
    'infoTitle': 'How it works',
    'step1k': '1',
    'step1v': 'Pick your car from the dropdowns.',
    'step2k': '2',
    'step2v': 'Photograph the car following the eight boxes.',
    'step3k': '3',
    'step3v': 'You get a request ID on screen and by email.',
    'step4k': '4',
    'step4v': 'Red light = under review. Green light = price ready.',
    'privTitle': 'Privacy',
    'privBody': 'Your photos and videos are deleted from the server automatically after 3 or 7 days, whichever you chose. We never share them.',
    'cTitle': 'Contact us',
    'cEmail': 'Email',
    'cWeb': 'Website',
    'devCredit': 'Developed by Farooq',
    'termsTitle': 'Terms & Conditions',
    'privacyTitle': 'Privacy Policy',
    'extraLink1Label': '',
    'extraLink2Label': '',
    'navEval': 'Evaluate',
    'navStatus': 'Status',
    'navInfo': 'Info',
    'navSupport': 'Support',
    'supportTitle': 'Support & suggestions',
    'supportIntro': 'Ran into a problem? Have a suggestion or a question? Write to us here and we will reply.',
    'supKind': 'What is this about?',
    'supMsg': 'Your message',
    'supMsgPh': 'Describe it in detail — for example: my car make was not in the list.',
    'supReach': 'Leave an email or a mobile number so we can reply — either one is enough.',
    'supRef': 'Request ID (if any)',
    'supSend': 'Send message',
    'supSending': 'Sending…',
    'supThanksT': 'Your message has been sent',
    'supportThanks': 'We have your message, thank you. We will get back to you on the email or number you gave.',
    'supRefNo': 'Reference',
    'supAnother': 'Send another message',
    'errSupMsg': 'Please write your message first (at least 10 characters).',
    'errSupContact': 'Please leave a valid email or a mobile number so we can reply.',
    'errSupMany': 'That is a lot of messages in a short time. Please try again later.',
    'supFollowT': 'Follow up on a message',
    'supFollowS': 'Have a reference number? Enter it to see whether we have read your message and replied.',
    'supKeep': 'Keep this number — you can check your message with it any time. We have emailed it to you too.',
    'errSupId': 'Please enter the full reference number.',
    'errSupNotFound': 'We could not find that reference. Please check and try again.',
    'supStNew': 'Received — not read yet',
    'supStSeen': 'Read',
    'supStReplied': 'Replied',
    'supYourMsg': 'Your message',
    'supOurReply': 'Our reply',
    'supSentOn': 'Sent',
    'pdfDownload': 'Download the valuation report (PDF)',
    'footer': 'Evaluate Your Car',
    'errFields': 'Please fill in the make, class, model, year and mileage.',
    'errModel': 'Please enter the model / trim.',
    'errKm': 'Please enter the mileage in numbers (km).',
    'errMissing': 'Still needed: {list}',
    'errVideoMax': 'Maximum {n} video clips.',
    'errReportMax': 'Maximum {n} report file(s).',
    'errReportType': 'The report must be a PDF or a photo.',
    'errBig': 'File "{f}" is too large (limit {n} MB).',
    'errName': 'Please enter your name.',
    'errPhone': 'Please enter a valid mobile number.',
    'errEmail': 'Please enter a valid email address.',
    'errNet': 'Could not send. Check your connection and try again.',
    'errId': 'Enter the 6-character request ID.',
    'errNotFound': 'We could not find that ID. Please check and try again.',
    'counterOk': '{a} photos — all required angles done ✔',
    'counterBad': '{a} of {b} required photos',
    'underReview': 'Under review',
    'underReviewSub': 'We have your request. We will email the price as soon as it is ready.',
    'ready': 'Valuation ready',
    'readySub': 'This is the estimated price for your car.',
    'priceLabel': 'Estimated price',
    'priceRange': 'Estimated price range',
    'carLabel': 'Car',
    'idLabel': 'Request ID',
    'sentAt': 'Submitted',
    'filesUntil': 'Files deleted on',
    'filesCount': 'Files',
    'photosW': 'photos',
    'videosW': 'video',
    'removed': 'Removed',
    'noteLabel': 'Note from our team',
  },
};
